load( "@rules_cc//cc:defs.bzl", "cc_test", "cc_library" )

cc_test(
    name = "reed-solomon-decoders-tests",
    srcs = glob([
        "*.cpp",
    ]),
    deps = [
        "//reed-solomon-codes",
        "//reed-solomon-decoders",
        "//imports/thirdparty/GoogleTest:GoogleTest",
        "//imports/thirdparty/GoogleTest:GoogleTest-Main",
    ],
    visibility = ["//visibility:public"],
)
