load( "@rules_cc//cc:defs.bzl", "cc_test", "cc_library" )

cc_library(
    name = "schemas",
    testonly = True,
    hdrs = glob([
        "*.h"
    ]),
    srcs = glob([
        "*.cpp",
    ]),
    deps = [
        "//cpp-helpers",
        "//reed-solomon-codes",
        "//reed-solomon-decoders",
        "//tests/finite-fields-tests:test-helpers",
    ],
    visibility = ["//visibility:public"],
)

