load( "@rules_cc//cc:defs.bzl", "cc_test" )

cc_test(
    name = "reed-solomon-codes-test",
    srcs = glob([
        "*_Tests.cpp",
    ]),
    deps = [
        "//reed-solomon-codes",
        "//finite-fields-tests:test-data",
        "//imports/thirdparty/GoogleTest:GoogleTest",
        "//imports/thirdparty/GoogleTest:GoogleTest-Main",
    ],
    visibility = ["//visibility:public"],
)
