load( "@rules_cc//cc:defs.bzl", "cc_library" )

cc_library(
    name = "finite-fields",
    hdrs = glob([
        "*.h"
    ]),
    deps = [
        "//container-helpers",
        "//cpp-helpers",
        "//elementary-mathematical-functions",
        "//elementary-number-theory",
        "//integer-packing-helpers",
    ],
    visibility = ["//visibility:public"],
)
