load( "@rules_cc//cc:defs.bzl", "cc_test", "cc_library" )

cc_test(
    name = "container-helpers-tests",
    srcs = glob([
        "*.cpp"
    ]),
    deps = [
        "//container-helpers",
        "//finite-fields",
        "//imports/thirdparty/GoogleTest:GoogleTest",
        "//imports/thirdparty/GoogleTest:GoogleTest-Main",
    ],
    visibility = ["//visibility:public"],
)

