load( "@rules_cc//cc:defs.bzl", "cc_test", "cc_library" )

cc_library(
    name = "test-data",
    testonly = True,
    hdrs = glob([
        "test-data/*.h"
    ]),
    deps = [
        "//finite-fields",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "binary-helpers",
    testonly = True,
    hdrs = glob([
        "binary-helpers/*.h"
    ]),
    deps = [
        "//finite-fields",
        "//integer-packing-helpers",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "test-helpers",
    testonly = True,
    srcs = glob([
        "helpers/*.h",
    ]),
    deps = [
        "//finite-fields",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "test-data-tests",
    srcs = glob([
        "test-data/*_Tests.cpp"
    ]),
    deps = [
        ":test-data",
        "//imports/thirdparty/GoogleTest:GoogleTest",
        "//imports/thirdparty/GoogleTest:GoogleTest-Main",
    ],
)

cc_test(
    name = "finite-fields-tests",
    srcs = glob([
        "*.cpp",
    ]),
    deps = [
        ":test-data",
        "//finite-fields",
        "//finite-fields-tests:test-helpers",
        "//imports/thirdparty/GoogleTest:GoogleTest",
        "//imports/thirdparty/GoogleTest:GoogleTest-Main",
    ],
    visibility = ["//visibility:public"],
)
