#pragma once

#include "finite-fields/FiniteFieldsOfSizePrimeToAPower.h"

#include "elementary-number-theory/Typedef.h"

#include <array>

// As part of building the ability to create any read solomon codes we need to create polynomials over finite fields of any possible size.
//   All codewords in ReedSolomon codes are generated by evaluating polynomials over finite fileds.

template <integer Prime, integer Exponent, integer MaxDegree>
class PolynomialOverFiniteField
{
	// static_assert( IsPrime(Prime) );
	static_assert( MaxDegree >= 0, "" );
	
	// Galois Fields of size q (where q == p**k)
	using GFq = ElementOfFiniteField<Prime,Exponent>;

public:
	static constexpr size_t GetCapacity()
	{
		return MaxDegree+1;
	}
	std::array<GFq, GetCapacity()> coefficients;

public:
	PolynomialOverFiniteField( std::array<GFq, GetCapacity()> Input )
		: coefficients( Input )
	{};
	
	constexpr GFq operator()(const GFq& a) const
	{
		auto running_multiple = a;
		GFq running_result = coefficients.at( 0 );
		for( size_t coefficient_index =1; coefficient_index < coefficients.size(); coefficient_index++ )
		{
			running_result = running_result + ( coefficients.at( coefficient_index ) * running_multiple );
			running_multiple = running_multiple * a;
		}

		return running_result;
	}
};
