#pragma once

#include "finite-fields/FiniteFieldsOfSizePrimeToAPower.h"
#include "polynomials-base/PolynomialsOverField.h"

// As part of building the ability to create any read solomon codes we need to create polynomials over finite fields of any possible size.
//   All codewords in ReedSolomon codes are generated by evaluating polynomials over finite fileds.

template <integer Prime, integer Exponent, integer MaxDegree>
using PolynomialOverFiniteField = PolynomialOverField<MaxDegree,ElementOfFiniteField<Prime,Exponent>>;
