load( "@rules_cc//cc:defs.bzl", "cc_test" )

cc_test(
    name = "finite-fields-polynomials-tests",
    srcs = glob([
        "*_Tests.cpp",
    ]),
    deps = [
        "//finite-fields-polynomials",
        "//finite-fields-tests:test-data",
        "//finite-fields-tests:test-helpers",
        "//imports/thirdparty/GoogleTest:GoogleTest",
        "//imports/thirdparty/GoogleTest:GoogleTest-Main",
    ],
    visibility = ["//visibility:public"],
)
