load( "@rules_cc//cc:defs.bzl", "cc_library" )

cc_library(
    name = "reed-solomon-decoders-tmp",
    hdrs = glob([
        "*.h"
    ]),
    deps = [
        "//container-helpers",
        "//finite-fields-extensions-tmp",
        "//reed-solomon-codes-tmp",
    ],
    visibility = ["//visibility:public"],
)
