load( "@rules_cc//cc:defs.bzl", "cc_test", "cc_library" )

cc_library(
    name = "test-helpers",
    srcs = glob([
        "helpers/*.h",
    ]),
    deps = [
        "//reed-solomon-codes",
        "//reed-solomon-decoders",
        "//imports/thirdparty/GoogleTest:GoogleTest",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "reed-solomon-decoders-tests",
    srcs = glob([
        "*.cpp",
    ]),
    deps = [
        ":test-helpers",
        "//reed-solomon-codes",
        "//reed-solomon-decoders",
        "//tests/finite-fields-tests:test-helpers",
        "//imports/thirdparty/GoogleTest:GoogleTest",
        "//imports/thirdparty/GoogleTest:GoogleTest-Main",
    ],
)
